stages:
  - build
  - test
  - deploy

default:
  image: node

.standard_rules:
 rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  
build_job:
  stage: build
  image: node
  extends:
    - .standard_rules
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - "build/"

test_markdown:
  stage: test
  extends:
    - .standard_rules
  image: node
  dependencies: []
  script:
    - npm install markdownlint-cli2 --global
    - markdownlint-cli2 -v
    - markdownlint-cli2 "blog/**/*.md" "docs/**/*.md"
  allow_failure: true

test_html:
  stage: test
  extends:
    - .standard_rules
  image: node
  dependencies:
    - build_job
  script:
    - npm install --save-dev htmlhint
    - npx htmlhint --version
    - npx htmlhint build/
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  dependencies:
    - build_job
  script:
    - mv build/ public
  artifacts:
    paths: 
      - "public/"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH